## LANGUAGE
defaultContentLanguage: en

## ADVANCED
build:
  buildStats:
    disableClasses: false
    disableIDs: true
    disableTags: false
    enable: true
enableRobotsTXT: true
imaging:
  quality: 75
markup:
  tableOfContents:
    ordered: true
  goldmark:
    renderer:
      unsafe: true
pagination:
  pagerSize: 9
removePathAccents: true
